src/Andrii.Web.Mvc/Models/Devices/DeviceListViewModel.cs
using Andrii.Devices.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Andrii.Web.Models.Devices
{
    public class DeviceListViewModel
    {
        public IReadOnlyList<DeviceDto> Devices { get; set; }

    }
}

src/Andrii.Web.Mvc/Models/Devices/DeviceStatistics.cs
using Andrii.Device.Dto;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Andrii.Web.Models.Devices
{
    public class DeviceStatistics
    {
        public IReadOnlyList<GroupedInfluxData> GroupedInfluxData { get; set; }
        public IReadOnlyList<DaySum> DaySum { get; set; }
        public DateTime dateTime;
        public string Name;
    }
}

src/Andrii.Web.Mvc/Models/Devices/EditDeviceModalViewModel.cs
using Andrii.Devices.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Andrii.Web.Models.Devices
{
    public class EditDeviceModalViewModel
    {
        public DeviceDto Device { get; set; }
    }
}

src/Andrii.Web.Mvc/Controllers/DevicesController.cs
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using Abp.Web.Models;
using AdysTech.InfluxDB.Client.Net;
using Andrii.Authorization;
using Andrii.Controllers;
using Andrii.Device.Dto;
using Andrii.Devices;
using Andrii.Devices.Dto;
using Andrii.Users.Dto;
using Andrii.Web.Models.Devices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Newtonsoft.Json;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Runtime.Serialization.Json;
using System.Threading.Tasks;

namespace Andrii.Web.Controllers
{
    [AbpMvcAuthorize(PermissionNames.Pages_Devices)]
    public class DevicesController : AndriiControllerBase
    {
        private readonly IDeviceAppService _deviceAppService;
        public DevicesController(IDeviceAppService deviceAppService)
        {
            _deviceAppService = deviceAppService;
        }

        public async Task<ActionResult> Index()
        {
            var devices = (await _deviceAppService.GetAll(new PagedUserResultRequestDto { MaxResultCount = int.MaxValue })).Items;
            var model = new DeviceListViewModel
            {
                Devices = devices
            };
            return View(model);
        }

        public async Task<ActionResult> Statistics(DateTime dateTime)
        {
            var groupedInfluxData = await _deviceAppService.Differences(dateTime);

            var model = new DeviceStatistics
            {
                GroupedInfluxData = groupedInfluxData
            };
            return View(model);
        }

        public async Task<ActionResult> DeviceStatistics(string name)
        {
            //DateTime dateTime = DateTime.Today.AddDays(-1);

            //var groupedInfluxData = await _deviceAppService.Difference(dateTime, name);

            var model = new DeviceStatistics
            {
                Name = name
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Differences([FromBody]DeviceStatistics deviceStatistics)
        {
            var groupedInfluxData = await _deviceAppService.Differences(deviceStatistics.dateTime.Date);
            var model = new DeviceStatistics
            {
                GroupedInfluxData = groupedInfluxData,
                dateTime = deviceStatistics.dateTime
            };
          
            return Json(model);
        }

        [HttpPost]
        public async Task<IActionResult> Difference([FromBody]DeviceStatistics deviceStatistics)
        {
            var groupedInfluxData = await _deviceAppService.Difference(deviceStatistics.dateTime.Date, deviceStatistics.Name);
            var model = new DeviceStatistics
            {
                GroupedInfluxData = groupedInfluxData,
                dateTime = deviceStatistics.dateTime
            };

            return Json(model);
        }

        public async Task<ActionResult> EditDeviceModal(long deviceId)
        {
            var devices = await _deviceAppService.Get(new EntityDto<long>(deviceId));
            var model = new EditDeviceModalViewModel
            {
                Device = devices
            };
            return View("_EditDeviceModal", model);
        }

        [HttpPost]
        public async Task<IActionResult> Excel(string dateTime)
        {
            DateTime date = DateTime.ParseExact(dateTime, "dd/MM/yyyy", null);

            var comlumHeadrs = new string[]
            {
                "Time",
                "Value"
            };

            byte[] result;

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("Statistics");
                using (var cells = worksheet.Cells[1, 1, 1, 2])
                {
                    cells.Style.Font.Bold = true;
                }
                for (var i = 0; i < comlumHeadrs.Count(); i++)
                {
                    worksheet.Cells[2, i + 1].Value = comlumHeadrs[i];
                }
                var groupedInfluxData = await _deviceAppService.Differences(date);

                var j = 3;
                worksheet.Cells["A1"].Value = "Date:";
                worksheet.Cells["B1"].Value = dateTime;
                
                foreach (var item in groupedInfluxData)
                {
                    worksheet.Cells["A" + j].Style.Numberformat.Format = "hh:ss:ms";
                    worksheet.Cells["A" + j].Value = item.Time;
                    worksheet.Cells["B" + j].Value = item.Value;

                    j++;
                }
                result = package.GetAsByteArray();
            }

            return File(result, "application/ms-excel", $"Statistics.xlsx");
        }
    }
}

src/Andrii.Web.Mvc/Views/Devices/DeviceStatistics.cshtml
@using Abp.Authorization.Users
@using Andrii.Web.Startup
@using Andrii.Devices.Dto
@model Andrii.Web.Models.Devices.DeviceStatistics
@{
    ViewBag.CurrentPageName = PageNames.Devices;
}
@section scripts
    {
    <environment names="Development">
        <script src="~/view-resources/Views/Devices/Index.js" asp-append-version="true"></script>
    </environment>
}

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css" rel="stylesheet" />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/emn178/chartjs-plugin-labels/src/chartjs-plugin-labels.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        var name = $("#routeDataId").val();

        var dateBefore = new Date();
        dateBefore.setDate(dateBefore.getDate() - 1);

        var deviceStatistics = {
            dateTime: dateBefore,
            Name: name
        };

        abp.ajax({
            url: '/Devices/Difference',
            data: JSON.stringify(deviceStatistics),
            dataType: "json"
        }).done(function (data) {
            abp.notify.success('success');

            var label = data.groupedInfluxData.map(function (e) {
                return e.timeString;
            });
            var values = data.groupedInfluxData.map(function (e) {
                return e.value;
            });

            $('table#TableID').remove();

            var table = '<table class="table" id="TableID"><thead><tr><th>@L("Time")</th><th>@L("Value")</th></tr></thead><tbody></tbody>';
            $('div#appendTable').append(table);

            $.each(data.groupedInfluxData, function (key, value) {
                var tr = '<tr class="trTableID">' +
                    '<td>' + value.time.split('T')[1].split(':00Z')[0] + '</td>' +
                    '<td>' + value.value + '</td></tr>';
                $('#TableID tbody').append(tr);
            });

            $(function () {
                var data = {
                    labels: label,
                    datasets: [{
                        backgroundColor:
                            'rgba(255, 99, 132, 0.2)',
                        data: values,
                        borderColor: "#3e95cd",
                        fill: false,
                        lineTension: 0.1
                    }]
                };
                var options = {
                    maintainAspectRatio: true,
                    legend: {
                        display: false,
                    },
                    scales: {
                        yAxes: [{
                            ticks: {
                                display: true
                            },
                            gridLines: {
                                display: true
                            }
                        }],
                        xAxes: [{
                            ticks: {
                                display: true
                            },
                            gridLines: {
                                display: true
                            }
                        }]
                    }
                };

                $("canvas#chartreport").remove();
                $("#divChart").append('<canvas id="chartreport"></canvas>');
                var ctx = document.getElementById("chartreport").getContext("2d");
                var chart = new Chart(ctx, {
                    options: options,
                    data: data,
                    type: 'line'
                });
            });
        });
    });
</script>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    @L("Statistics")
                </h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a id="RefreshButton" href="javascript:void(0);" class="waves-effect waves-block"><i class="material-icons">refresh</i>@L("Refresh")</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body table-responsive">
                <input type="hidden" value="@Model.Name" id="routeDataId" />
                <div class="col-sm-3">
                    @using (Html.BeginForm("Excel", "Devices"))
                    {
                        <input name="dateTime" type="text" class="form-control" id="datetimepicker1" />
                        <input type="submit" value="Download Excel" class="btn btn-success" />
                    }
                    <script type="text/javascript">
                        var dateNow = new Date();
                        var date = new Date();
                        $('#datetimepicker1').datetimepicker({
                            format: 'DD/MM/YYYY', defaultDate: date.setDate(date.getDate() - 1), maxDate: moment(), disabledDates: [dateNow]
                        }).on('dp.change', function (e) {
                            var formatedValue = e.date.format(e.date._f);

                            var split = formatedValue.split("/");
                            var newDate = split[1] + "/" + split[0] + "/" + split[2];
                            console.log(newDate);

                            var name = $("#routeDataId").val();

                            var deviceStatistics = {
                                dateTime: newDate,
                                Name: name
                            };

                            abp.ajax({
                                url: '/Devices/Difference',
                                data: JSON.stringify(deviceStatistics),
                                dataType: "json"
                            }).done(function (data) {
                                abp.notify.success('success');

                                var label = data.groupedInfluxData.map(function (e) {
                                    return e.timeString;
                                });
                                var values = data.groupedInfluxData.map(function (e) {
                                    return e.value;
                                });

                                $('table#TableID').remove();

                                var table = '<table class="table" id="TableID"><thead><tr><th>@L("Time")</th><th>@L("Value")</th></tr></thead><tbody></tbody>';
                                $('div#appendTable').append(table);

                                $.each(data.groupedInfluxData, function (key, value) {
                                    var tr = '<tr class="trTableID">' +
                                        '<td>' + value.time.split('T')[1].split(':00Z')[0] + '</td>' +
                                        '<td>' + value.value + '</td></tr>';
                                    $('#TableID tbody').append(tr);
                                });

                                $(function () {
                                    var data = {
                                        labels: label,
                                        datasets: [{
                                            backgroundColor:
                                                'rgba(255, 99, 132, 0.2)',
                                            data: values,
                                            borderColor: "#3e95cd",
                                            fill: false,
                                            lineTension: 0.1
                                        }]
                                    };
                                    var options = {
                                        maintainAspectRatio: true,
                                        legend: {
                                            display: false,
                                        },
                                        scales: {
                                            yAxes: [{
                                                ticks: {
                                                    display: true
                                                },
                                                gridLines: {
                                                    display: true
                                                }
                                            }],
                                            xAxes: [{
                                                ticks: {
                                                    display: true
                                                },
                                                gridLines: {
                                                    display: true
                                                }
                                            }]
                                        }
                                    };

                                    $("canvas#chartreport").remove();
                                    $("#divChart").append('<canvas id="chartreport"></canvas>');
                                    var ctx = document.getElementById("chartreport").getContext("2d");
                                    var chart = new Chart(ctx, {
                                        options: options,
                                        data: data,
                                        type: 'line'
                                    });
                                });
                            });
                        });
                    </script>
                </div>
                <div id="appendTable"></div>
            </div>
            <div>
                <div id="divChart">
                    <canvas id="chartreport"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>

src/Andrii.Web.Mvc/Views/Devices/Index.cshtml
@using Abp.Authorization.Users
@using Andrii.Web.Startup
@model Andrii.Web.Models.Devices.DeviceListViewModel
@{
    ViewBag.CurrentPageName = PageNames.Devices; // The menu item will be active for this page.
}

@section scripts
    {
    <environment names="Development">
        <script src="~/view-resources/Views/Devices/Index.js" asp-append-version="true"></script>
    </environment>
}
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    @L("Devices")
                </h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a id="RefreshButton" href="javascript:void(0);" class="waves-effect waves-block"><i class="material-icons">refresh</i>@L("Refresh")</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>@L("Name")</th>
                            <th>@L("Description")</th>
                            <th>@L("Actions")</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var device in Model.Devices)
                        {
                            <tr>
                                <td>@device.Name</td>
                                <td>@device.Description</td>
                                <td class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">menu</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="#" class="waves-effect waves-block edit-device" data-device-id="@device.Id" data-toggle="modal" data-target="#DeviceEditModal"><i class="material-icons">edit</i>@L("Edit")</a></li>
                                        <li><a href="#" class="waves-effect waves-block delete-device" data-device-id="@device.Id" data-device-name="@device.Name"><i class="material-icons">delete_sweep</i>@L("Delete")</a></li>
                                        <li><a asp-action="DeviceStatistics" asp-route-name="@device.Name" data-device-name="@device.Name" class="waves-effect waves-block"><i class="material-icons">show_chart</i>@L("Statistics")</a></li>
                                    </ul>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <button type="button" class="btn btn-primary btn-circle waves-effect waves-circle waves-float pull-right" data-toggle="modal" data-target="#DeviceCreateModal">
                    <i class="material-icons">add</i>
                </button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="DeviceCreateModal" tabindex="-1" role="dialog" aria-labelledby="DeviceCreateModalLabel" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                    <span>@L("CreateNewDevice")</span>
                </h4>
            </div>
            <div class="modal-body">
                <form name="deviceCreateForm" role="form" novalidate>

                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane animated fadeIn active" id="create-movie-details">
                            <div class="row clearfix" style="margin-top:10px;">
                                <div class="col-sm-12">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            <input class="form-control" name="Name" type="text" required>
                                            <label class="form-label">@L("Name")</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-sm-12">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            <input type="text" name="Description" class="form-control" required>
                                            <label class="form-label">@L("Description")</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">@L("Cancel")</button>
                        <button type="submit" class="btn btn-primary waves-effect">@L("Save")</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="DeviceEditModal" tabindex="-1" role="dialog" aria-labelledby="DeviceEditModalLabel" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>

src/Andrii.Web.Mvc/Views/Devices/_EditDeviceModal.cshtml
@using Andrii.Web.Models.Common.Modals
@model Andrii.Web.Models.Devices.EditDeviceModalViewModel
@{
    Layout = null;
}
@Html.Partial("~/Views/Shared/Modals/_ModalHeader.cshtml", new ModalHeaderViewModel(L("EditDevice")))
<div class="modal-body">
    <form name="DeviceEditForm" role="form" novalidate>
        <input type="hidden" name="Id" value="@Model.Device.Id" />
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane animated fadeIn active">
                <div class="row clearfix" style="margin-top:10px;">
                    <div class="col-sm-12">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input id="name" type="text" name="Name" value="@Model.Device.Name" class="form-control validate" required>
                                <label for="name" class="form-label">@L("Name")</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row clearfix">
                    <div class="col-sm-12">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input id="description" type="text" name="Description" class="form-control validate" required value="@Model.Device.Description">
                                <label for="description" class="form-label">@L("Description")</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@Html.Partial("~/Views/Shared/Modals/_ModalFooterWithSaveAndCancel.cshtml")
<script src="~/view-resources/Views/Devices/_EditDeviceModal.js" asp-append-version="true"></script>